version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: cgram
    network_mode: "host"
    #ports:
    # - "5432::5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app-back:
    image: back-v1
    network_mode: "host"
    #ports:
    # - "3005:3000"
    volumes:
      - multer-uploads:/src/app/images
    depends_on:
      - db

  app-front:
    image: front-v1
    network_mode: "host"
    depends_on:
      - app-back
  nginx:
    image: nginx:alpine
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-back
      - app-front
      - db
    #ports:
    # - "80:80"

    #  pgadmin:
    #    image: dpage/pgadmin4
    #    environment:
    #      PGADMIN_DEFAULT_EMAIL: admin@minusone.com
    #      PGADMIN_DEFAULT_PASSWORD: admin
    #    ports:
    #      - "8081:80"
    #    depends_on:
    #      - db

volumes:
  multer-uploads:
  postgres_data:
